apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apic-publish-products-apis-pipeline
spec:
  params:
  tasks:
    - name: apic-publish-products-apis
      params:
      # GitHub url where the pipeline scripts are stored. These are the scripts the pipeline will execute.
      - name: git-apic-pipeline-git-url
        value: 'https://github.ibm.com/techaeta/apic-pipeline.git'
      # Github branch for the pipeline scripts.
      - name: git-apic-pipeline-git-branch
        value: 'master'
      # GitHub url where the products and APIs definitions are stored.
      - name: git-apic-yaml-url
        value: 'https://github.ibm.com/techaeta/apic-yaml/'
      # GitHub branch for the products and APIs.
      - name: git-apic-yaml-branch
        value: 'master'
      # Path to where the products definitions are stored within your GitHub repository.
      - name: git-products-path
        value: 'Demo/Products'
      # Path to where the APIs definitions are stored within your GitHub repository.
      - name: git-apis-path
        value: 'Demo/APIs'
      # OpenShift project where your IBM API Connect Cluster v10 has been deployed into.
      - name: apic-project
        value: prod
      # Debug flag
      - name: debug
        value: "True"
      taskRef:
        name: apic-publish-products-apis